# Copyright 2019 Katy Coe - http://www.hearthcode.org - http://www.djkaty.com
# All rights reserved.

# Generate Tests.cs
$testGen = "$PSScriptRoot/Tests.cs"
$bin = "$PSScriptRoot/TestBinaries"

echo @"
// THIS FILE IS AUTO-GENERATED BY GENERATE-TESTS.PS1
// DO NOT EDIT

using NUnit.Framework;

namespace Il2CppInspector
{
	public partial class TestRunner
	{
"@ > $testGen

gci -Directory $bin | % {
	echo @"
		[Test]
		public void $($_.Name -Replace '\W','_')() {
			runTest(@"$($_.FullName)");
		}

"@ >> $testGen
}

echo @"
	}
}
"@ >> $testGen