//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Il2CppInspector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Il2CppInspector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated C++ file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
        ///// DLL entry point
        ///
        ///#define WIN32_LEAN_AND_MEAN
        ///#include &lt;windows.h&gt;
        ///#include &quot;il2cpp-init.h&quot;
        ///#include &quot;main.h&quot;
        ///
        ///// DLL entry point
        ///BOOL APIENTRY DllMain( HMODULE hModule,
        ///                       DWORD  ul_reason_for_call,
        ///                       LPVOID lpReserved
        ///                     )
        ///{
        ///    switch (ul_reason_for_call)
        ///    {
        ///    case DLL_PROCESS_ATTACH:
        ///        init_il2cpp();
        ///        CreateThread(NULL, 0, (LPTHREAD_S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cpp_DLLMainCpp {
            get {
                return ResourceManager.GetString("Cpp-DLLMainCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated C++ file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
        ///// Helper functions
        ///
        ///#define WIN32_LEAN_AND_MEAN
        ///#include &lt;windows.h&gt;
        ///#include &lt;string&gt;
        ///#include &quot;helpers.h&quot;
        ///
        ///// Log file location
        ///extern const LPCWSTR LOG_FILE;
        ///
        ///// Helper function to get the module base address
        ///uintptr_t GetBaseAddress() {
        ///    return (uintptr_t) GetModuleHandleW(L&quot;GameAssembly.dll&quot;);
        ///}
        ///
        ///// Helper function to append text to a file
        ///void LogWrite(std::string text) {
        ///    HANDLE hfile = CreateFileW(LOG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cpp_HelpersCpp {
            get {
                return ResourceManager.GetString("Cpp-HelpersCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated C++ file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
        ///// Helper functions
        ///
        ///#pragma once
        ///
        ///#include &lt;string&gt;
        ///#include &lt;sstream&gt;
        ///#include &lt;iomanip&gt;
        ///
        ///// Helper function to get the module base address
        ///uintptr_t GetBaseAddress();
        ///
        ///// Helper function to append text to a file
        ///void LogWrite(std::string text);
        ///
        ///// Helper function to open a new console window and redirect stdout there
        ///void NewConsole();
        ///
        ///// Helper function to convert a pointer to hex
        ///template&lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cpp_HelpersH {
            get {
                return ResourceManager.GetString("Cpp-HelpersH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated C++ file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
        ///// IL2CPP application data
        ///
        ///#pragma once
        ///
        ///#include &lt;cstdint&gt;
        ///
        ///// Application-specific types
        ///#include &quot;il2cpp-types.h&quot;
        ///
        ///// IL2CPP API function pointers
        ///#include &quot;il2cpp-api-functions-ptr.h&quot;
        ///
        ///// IL2CPP APIs
        ///#define DO_API(r, n, p) extern r (*n) p
        ///#include &quot;il2cpp-api-functions.h&quot;
        ///#undef DO_API
        ///
        ///// Application-specific functions
        ///#define DO_APP_FUNC(a, r, n, p) extern r (*n) p
        ///namespace app {
        ///	#incl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cpp_Il2CppAppDataH {
            get {
                return ResourceManager.GetString("Cpp-Il2CppAppDataH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated C++ file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
        ///// IL2CPP application initializer
        ///
        ///#include &quot;pch-il2cpp.h&quot;
        ///
        ///#include &quot;il2cpp-appdata.h&quot;
        ///#include &quot;il2cpp-init.h&quot;
        ///#include &quot;helpers.h&quot;
        ///
        ///// IL2CPP APIs
        ///#define DO_API(r, n, p) r (*n) p
        ///#include &quot;il2cpp-api-functions.h&quot;
        ///#undef DO_API
        ///
        ///// Application-specific functions
        ///#define DO_APP_FUNC(a, r, n, p) r (*n) p
        ///namespace app {
        ///#include &quot;il2cpp-functions.h&quot;
        ///}
        ///#undef DO_APP_FUNC
        ///
        ///// TypeInfo pointers
        ///# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cpp_Il2CppInitCpp {
            get {
                return ResourceManager.GetString("Cpp-Il2CppInitCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated C++ file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
        ///// IL2CPP application initializer
        ///
        ///#pragma once
        ///
        ///// IL2CPP application initializer
        ///void init_il2cpp();.
        /// </summary>
        internal static string Cpp_Il2CppInitH {
            get {
                return ResourceManager.GetString("Cpp_Il2CppInitH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated C++ file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
        ///// Custom injected code entry point
        ///
        ///#include &quot;pch-il2cpp.h&quot;
        ///
        ///#define WIN32_LEAN_AND_MEAN
        ///#include &lt;Windows.h&gt;
        ///#include &lt;iostream&gt;
        ///#include &quot;il2cpp-appdata.h&quot;
        ///#include &quot;helpers.h&quot;
        ///
        ///using namespace app;
        ///
        ///// Set the name of your log file here
        ///extern const LPCWSTR LOG_FILE = L&quot;il2cpp-log.txt&quot;;
        ///
        ///// Custom injected code entry point
        ///void Run()
        ///{
        ///    // If you would like to write to a log file, specify the name above and u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cpp_MainCpp {
            get {
                return ResourceManager.GetString("Cpp-MainCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated C++ file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
        ///// Custom injected code entry point
        ///
        ///#pragma once
        ///
        ///// Custom injected code entry point
        ///void Run();.
        /// </summary>
        internal static string Cpp_MainH {
            get {
                return ResourceManager.GetString("Cpp-MainH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // pch.cpp: source file corresponding to the pre-compiled header
        ///
        ///#include &quot;pch-il2cpp.h&quot;
        ///
        ///// When you are using pre-compiled headers, this source file is necessary for compilation to succeed..
        /// </summary>
        internal static string Cpp_PCHIl2Cpp {
            get {
                return ResourceManager.GetString("Cpp-PCHIl2Cpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // pch.h: This is a precompiled header file.
        ///// Files listed below are compiled only once, improving build performance for future builds.
        ///// This also affects IntelliSense performance, including code completion and many code browsing features.
        ///// However, files listed here are ALL re-compiled if any one of them is updated between builds.
        ///// Do not add files here that you will be updating frequently as this negates the performance advantage.
        ///
        ///#ifndef PCH_IL2CPP_H
        ///#define PCH_IL2CPP_H
        ///
        ///// add headers [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cpp_PCHIl2CppH {
            get {
                return ResourceManager.GetString("Cpp-PCHIl2CppH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;ItemGroup&gt;
        ///    &lt;ClCompile Include=&quot;user\main.cpp&quot;&gt;
        ///      &lt;Filter&gt;user&lt;/Filter&gt;
        ///    &lt;/ClCompile&gt;
        ///    &lt;ClCompile Include=&quot;framework\dllmain.cpp&quot;&gt;
        ///      &lt;Filter&gt;framework&lt;/Filter&gt;
        ///    &lt;/ClCompile&gt;
        ///    &lt;ClCompile Include=&quot;framework\helpers.cpp&quot;&gt;
        ///      &lt;Filter&gt;framework&lt;/Filter&gt;
        ///    &lt;/ClCompile&gt;
        ///    &lt;ClCompile Include=&quot;framework\il2cpp-init.cpp&quot;&gt;
        ///      &lt;Filter&gt;framework&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CppProjFilters {
            get {
                return ResourceManager.GetString("CppProjFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;ItemGroup Label=&quot;ProjectConfigurations&quot;&gt;
        ///    &lt;ProjectConfiguration Include=&quot;Debug|Win32&quot;&gt;
        ///      &lt;Configuration&gt;Debug&lt;/Configuration&gt;
        ///      &lt;Platform&gt;Win32&lt;/Platform&gt;
        ///    &lt;/ProjectConfiguration&gt;
        ///    &lt;ProjectConfiguration Include=&quot;Release|Win32&quot;&gt;
        ///      &lt;Configuration&gt;Release&lt;/Configuration&gt;
        ///      &lt;Platform&gt;Win32&lt;/Platform&gt;
        ///    &lt;/ProjectConfiguration&gt;
        ///    &lt;ProjectCon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CppProjTemplate {
            get {
                return ResourceManager.GetString("CppProjTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio Version 16
        ///VisualStudioVersion = 16.0.30204.135
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}&quot;) = &quot;%PROJECTNAME%&quot;, &quot;%PROJECTFILE%&quot;, &quot;{%PROJECTGUID%}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		Debug|x64 = Debug|x64
        ///		Debug|x86 = Debug|x86
        ///		Release|x64 = Release|x64
        ///		Release|x86 = Release|x86
        ///	EndGlobalSection
        ///	GlobalSection(ProjectConfigurationPlatfo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CppSlnTemplate {
            get {
                return ResourceManager.GetString("CppSlnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;LangVersion&gt;latest&lt;/LangVersion&gt;
        ///  &lt;/PropertyGroup&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProjectGuid&gt;{%PROJECTGUID%}&lt;/ProjectGuid&gt;
        ///    &lt;!--&lt;ProductVersion/&gt;--&gt;
        ///    &lt;!--&lt;SchemaVersion/&gt;--&gt;
        ///    &lt;OutputType&gt;Li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CsProjTemplate {
            get {
                return ResourceManager.GetString("CsProjTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio Version 16
        ///%PROJECTDEFINITIONS%
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		Debug|Any CPU = Debug|Any CPU
        ///		Release|Any CPU = Release|Any CPU
        ///	EndGlobalSection
        ///	GlobalSection(ProjectConfigurationPlatforms) = postSolution
        ///%PROJECTCONFIGURATIONS%
        ///	EndGlobalSection
        ///	GlobalSection(SolutionProperties) = preSolution
        ///		HideSolutionNode = FALSE
        ///	EndGlobalSection
        ///EndGlobal
        ///.
        /// </summary>
        internal static string CsSlnTemplate {
            get {
                return ResourceManager.GetString("CsSlnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		{%PROJECTGUID%}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
        ///		{%PROJECTGUID%}.Debug|Any CPU.Build.0 = Debug|Any CPU
        ///		{%PROJECTGUID%}.Release|Any CPU.ActiveCfg = Release|Any CPU
        ///		{%PROJECTGUID%}.Release|Any CPU.Build.0 = Release|Any CPU
        ///.
        /// </summary>
        internal static string SlnProjectConfiguration {
            get {
                return ResourceManager.GetString("SlnProjectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;%PROJECTNAME%&quot;, &quot;%CSPROJRELATIVEPATH%&quot;, &quot;{%PROJECTGUID%}&quot;
        ///EndProject
        ///.
        /// </summary>
        internal static string SlnProjectDefinition {
            get {
                return ResourceManager.GetString("SlnProjectDefinition", resourceCulture);
            }
        }
    }
}
